import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    common: {
      dashboard: "Dashboard",
      foods: "Foods",
      history: "History",
      calendar: "Calendar",
      statistics: "Statistics",
      settings: "Settings",
      payment: "Payments",
      ingredients: "Ingredients & Grocery",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      loading: "Loading...",
      serviceOnline: "Service Online",
      messMaster: "Mess Master"
    },
    holiday: {
      badge: "HOLIDAY",
      title: "Holiday",
      isHoliday: "Marked as Holiday",
      holidayNotice: "This date is marked as a non-working holiday.",
      holidayDesc: "No lunch, ingredient, fresh-item, or purchase requirements are generated for this date.",
      markHolidayBtn: "Mark Holiday",
      markHolidayPromptTitle: "Mark as Holiday?",
      markHolidayPromptMsg: "This date will be treated as a non-working lunch day. No lunch, ingredient, fresh-item, or purchase requirements will be generated.",
      removeHolidayBtn: "Remove Holiday",
      removeHolidayPromptTitle: "Remove Holiday?",
      removeHolidayPromptMsg: "This date will return to a normal working day.",
      markedSuccess: "Date marked as Holiday successfully! 🎉",
      removedSuccess: "Holiday removed successfully. Normal working day restored!",
      calendarTag: "Holiday",
      noRequirements: "No Requirements"
    },
    topSection: {
      goodMorning: "Good Morning",
      goodAfternoon: "Good Afternoon",
      goodEvening: "Good Evening",
      master: "Master",
      subtitle: "Manage tomorrow's lunch and configure recipes in real-time.",
      autoGen: "Auto Generation",
      autoGeneration: "Auto Generation",
      active: "Active"
    },
    dashboard: {
      todayTitle: "Today's Lunch Menu",
      tomorrowTitle: "Tomorrow's Lunch Menu",
      timeRange: "1:00 PM – 2:00 PM",
      noTodayMenu: "No Menu generated for Today",
      noTodaySub: "Menus are auto-generated daily at 08:00 PM. Use the section below to plan tomorrow.",
      preparedServed: "Prepared & Served",
      notSelectedTitle: "Tomorrow's menu is currently not selected",
      notSelectedSub: "Click Roll & Select to trigger our custom recipe recommendation wheel.",
      btnRollSelect: "Roll & Select Menu",
      btnSkipMenu: "Skip Menu",
      btnMessageChef: "Message Chef",
      carouselTitle: "Selecting Tomorrow's Feast...",
      spinPrompt: "Click below to stop the wheel!",
      spinStopBtn: "Stop Wheel",
      availableRecipes: "Available Dishes Pool",
      availableRecipesSub: "Active recipes eligible for automatic daily scheduling.",
      dishes: "dishes",
      available: "Available",
      unavailable: "Unavailable",
      category: "Category",
      desc: "Description",
      tomorrowSelectedTitle: "Tomorrow's Lunch Selected",
      skipAlert: "Lunch skipped. Selecting next available menu item...",
      initAlert: "Tomorrow's Lunch menu generation initiated...",
      noAvailableFoods: "No Available Foods Found",
      noAvailableFoodsSub: "Please add some dishes in the Foods tab and make sure they are toggled as \"Available\" to start generating menus.",
      failedFetch: "Failed to fetch dashboard data"
    },
    foods: {
      title: "Food Items Directory",
      subtitle: "Add, edit, or disable culinary options for menu generation.",
      searchPlaceholder: "Search dishes by name or category...",
      addNew: "Add New Food",
      category: "Category",
      status: "Status",
      actions: "Actions",
      editDish: "Edit Food Item",
      addDish: "Add Food Item",
      dishName: "Dish Name",
      dishNameEn: "Dish Name (English)",
      dishNameTa: "Dish Name (Tamil)",
      dishDesc: "Description",
      dishDescEn: "Description (English)",
      dishDescTa: "Description (Tamil)",
      dishImage: "Dish Image",
      uploadPrompt: "Click to upload image or drag and drop",
      uploadFormats: "PNG, JPG, JPEG up to 10MB",
      saving: "Saving...",
      successAdd: "Food item added successfully!",
      successEdit: "Food item updated successfully!",
      failedFetch: "Failed to fetch food items",
      nameRequired: "Name is required",
      confirmDelete: "Are you sure you want to delete this food item?",
      successDelete: "Food item deleted successfully!",
      failedDelete: "Failed to delete food item",
      foodTypeLabel: "Food Type",
      vegLabel: "Veg",
      nonVegLabel: "Non-Veg"
    },
    history: {
      title: "Lunch History Logs",
      subtitle: "Review previously generated menus and skipped selections.",
      searchPlaceholder: "Search history by dish name or category...",
      monthFilterPlaceholder: "All Months",
      dish: "Dish",
      servedOn: "Served On",
      generatedAt: "Generated At",
      noHistoryRecords: "No history records found",
      noHistorySub: "Make sure you have generated lunch menus for yesterday, today or tomorrow.",
      failedFetchHistory: "Failed to fetch history logs"
    },
    calendar: {
      title: "Interactive Lunch Calendar",
      subtitle: "Plan and view menus for the current and upcoming weeks.",
      today: "Today",
      prev: "Prev",
      next: "Next",
      selectedMenuDetails: "Selected Menu Details",
      noSelectedMenu: "No Menu Generated",
      clickAnyDay: "Click any highlighted day to see details.",
      failedFetchFoods: "Failed to fetch available food items",
      Sunday: "Sun",
      Monday: "Mon",
      Tuesday: "Tue",
      Wednesday: "Wed",
      Thursday: "Thu",
      Friday: "Fri",
      Saturday: "Sat"
    },
    statistics: {
      title: "Culinary Insights & Stats",
      subtitle: "Analytics on recipe usage, categories, and skip rates.",
      totalDishes: "Total Dishes",
      activeDishes: "Active Dishes",
      inactiveDishes: "Inactive Dishes",
      mostServed: "Most Served Recipe",
      leastServed: "Least Served Recipe",
      skipRate: "Average Skip Rate",
      categoryDistribution: "Category Distribution",
      servedTimeline: "Served Timeline",
      noChartData: "No data available. Add foods in different categories.",
      totalGenerations: "Menus Generated",
      totalSkips: "Menus Skipped",
      availabilityChart: "Availability Summary"
    },
    settings: {
      title: "System Settings",
      subtitle: "Admin preferences and database seeding options.",
      dbSetup: "Database Setup",
      dbSetupSub: "Seed demo recipes to populate the dashboard immediately.",
      preseedTitle: "Pre-seed Premium Recipe Menu",
      preseedSub: "Adds 10 diverse dishes (Main courses, salads, desserts, beverages) complete with high-res images and culinary descriptions.",
      btnSeed: "Seed Recipes",
      seeding: "Seeding...",
      seedConfirm: "This will add 10 pre-configured dishes to your food list. Proceed?",
      seedSuccess: "Seeded database with 10 premium food items!",
      seedFailed: "Failed to seed database",
      schedulerConfig: "System Scheduler Config",
      schedulerSub: "MESS master background workers and automation status.",
      cronStatus: "Node-Cron Status",
      cronActive: "Active & Running",
      triggerFreq: "Trigger Frequency",
      triggerTime: "Daily at exactly 08:00 PM (20:00)",
      targetAction: "Target Action",
      targetActionDesc: "Generate tomorrow's menu avoiding previous 5-day selections",
      dangerousSettings: "Dangerous Settings",
      dangerousSub: "Destructive actions. Use with extreme caution.",
      resetDb: "Reset Database",
      resetDbSub: "Deletes all recipe items and generated menu selection logs. This cannot be undone.",
      btnReset: "Reset Data",
      resetConfirm: "CRITICAL WARNING: Are you absolutely sure you want to drop all data? This will clear all foods and menus.",
      resetInitiated: "Database reset initiated",
      resetFailed: "Reset failed",
      langSelect: "Select Language",
      langSelectDesc: "Choose your preferred user interface language.",
      chefConfig: "Chef Communication Config",
      chefConfigSub: "Configure Chef contact details for sharing daily menus.",
      chefName: "Chef Name",
      chefPhone: "Chef Phone Number (with Country Code)",
      chefNamePlaceholder: "e.g. Ramu",
      chefPhonePlaceholder: "e.g. +919876543210",
      btnSaveChef: "Save Chef Config",
      chefConfigSaved: "Chef settings saved successfully!",
      paymentConfig: "Payment & QR Configuration",
      paymentConfigSub: "Configure UPI and Bank details for customer billing.",
      upiId: "UPI ID",
      upiName: "Display Name (UPI Account)",
      upiAmount: "Default Billing Amount (₹)",
      bankName: "Bank Name",
      bankAcc: "Bank Account Number",
      bankIfsc: "Bank IFSC Code",
      btnSavePayment: "Save Payment Config",
      paymentConfigSaved: "Payment configuration saved successfully!"
    },
    ingredients: {
      title: "Ingredients & Grocery Planning",
      subtitle: "Calculate daily meal requirements, manage storage stock, and plan monthly grocery purchases.",
      tabDaily: "Daily Requirements",
      tabStorage: "Grocery Storage",
      tabMonthly: "Monthly Planning",
      tabRecipes: "28 Dish Recipes",
      todayLunch: "Today's Lunch Menu",
      selectDate: "Select Date",
      employeesApplied: "Employees Applied for Lunch",
      employeesAppliedDesc: "Actual number of people who will eat lunch on this day.",
      baseRecipeNotice: "Base Recipe Serving Size: 10 Employees",
      formulaNotice: "Required Quantity = (Base Quantity / 10) × Actual Employees",
      groceryStorageHeader: "🏪 Grocery / Storage Items",
      groceryStorageSub: "Items eligible for inventory management. Compared against current storage.",
      freshItemsHeader: "🥬 Fresh Items Required Today",
      freshItemsSub: "Perishable items to procure fresh daily. Not deducted from long-term storage.",
      purchaseListHeader: "🛒 Today's Purchase List",
      purchaseListSub: "Items where Required Quantity exceeds Current Storage.",
      allStockSufficient: "✅ All required items are sufficiently in stock. No purchase needed today.",
      confirmDeductBtn: "Confirm & Deduct Used Stock",
      confirmDeductConfirm: "Are you sure you want to deduct today's grocery ingredients from storage inventory?",
      stockDeductedSuccess: "Stock deducted and updated successfully!",
      alreadyDeducted: "Stock already deducted for this lunch date",
      deductedOn: "Deducted on",
      itemName: "Ingredient Name",
      required: "Required",
      available: "Current Stock",
      purchaseNeeded: "Purchase Needed",
      remainingAfterLunch: "Remaining Stock",
      unit: "Unit",
      status: "Status",
      actions: "Actions",
      inStock: "In Stock",
      lowStock: "Low Stock",
      outOfStock: "Out of Stock",
      addStockTitle: "Add / Update Stock",
      setStock: "Set Absolute Stock",
      addAmount: "Add Quantity",
      minThreshold: "Min Alert Threshold",
      suggestedStock: "Suggested Standard Stock",
      updateStockSuccess: "Stock updated successfully!",
      monthlyTitle: "Monthly Grocery Procurement Plan",
      monthlySub: "Aggregated grocery requirements based on daily actual employee counts and scheduled menus.",
      monthlyTotalRequired: "Monthly Required",
      extraPurchaseRequired: "Additional Purchase Needed",
      totalDays: "Total Days",
      totalMeals: "Projected Employee Meals",
      totalGroceryTypes: "Storage Grocery Items",
      shortfallItems: "Items Requiring Purchase",
      copyList: "Copy Shopping List",
      listCopied: "Shopping list copied to clipboard!",
      shareWhatsapp: "Share on WhatsApp",
      saveCount: "Save Count",
      dishRecipeCount: "28 Pre-loaded Authentic Meals",
      searchDishes: "Search recipes or ingredients...",
      filterVeg: "Vegetarian Only",
      filterNonVeg: "Non-Vegetarian",
      filterAll: "All Dishes",
      storageStockSection: "STORAGE STOCK",
      storageStockSub: "Available grocery inventory with active stock (> 0)",
      outOfStockSection: "OUT OF STOCK",
      outOfStockSub: "Items with 0 stock requiring refill or procurement",
      noInStockItems: "No items currently in stock.",
      noOutOfStockItems: "All items are in stock!",
      editRecipe: "Edit Recipe",
      editRecipeTitle: "Edit Recipe & Ingredients",
      editRecipeSub: "Update base ingredients and proportions for 10 persons.",
      addIngredient: "Add Ingredient",
      removeIngredient: "Remove Ingredient",
      confirmRemoveIngredient: "Are you sure you want to remove this ingredient from the recipe?",
      saveRecipeChanges: "Save Changes",
      recipeUpdatedSuccess: "Recipe updated successfully! 🎉",
      recipeUpdateFailed: "Failed to update recipe",
      dishNameEn: "Dish Name (English)",
      dishNameTa: "Dish Name (Tamil)",
      foodType: "Food Type",
      category: "Category",
      description: "Description",
      basePersonsLabel: "Base Proportions Serving Size",
      ingredientNameEn: "Ingredient Name",
      ingredientNameTa: "Tamil Name",
      ingredientCategory: "Category",
      baseQuantity: "Base Qty (10p)",
      unit: "Unit",
      groceryCategory: "Grocery / Storage",
      freshCategory: "Fresh Produce",
      deleteStorageTitle: "Remove from Storage",
      confirmDeleteStorage: "Are you sure you want to remove this item from physical storage?",
      deleteStorageNote: "Recipe and food requirements will remain completely intact.",
      storageDeletedSuccess: "Storage item removed successfully"
    }
  },
  ta: {
    common: {
      dashboard: "டாஷ்போர்டு",
      foods: "உணவுகள்",
      history: "வரலாறு",
      calendar: "நாட்காட்டி",
      statistics: "புள்ளிவிவரங்கள்",
      settings: "அமைப்புகள்",
      payment: "பணம் செலுத்துதல்",
      ingredients: "மளிகை & தேவைகள்",
      save: "சேமி",
      cancel: "ரத்துசெய்",
      delete: "அழி",
      edit: "திருத்து",
      add: "சேர்",
      loading: "ஏற்றப்படுகிறது...",
      serviceOnline: "சேவை ஆன்லைனில் உள்ளது",
      messMaster: "மெஸ் மாஸ்டர்"
    },
    holiday: {
      badge: "விடுமுறை",
      title: "விடுமுறை",
      isHoliday: "விடுமுறை நாளாக குறிக்கப்பட்டுள்ளது",
      holidayNotice: "இந்த நாள் வேலை இல்லாத விடுமுறை நாளாகக் குறிக்கப்பட்டுள்ளது.",
      holidayDesc: "இந்த நாளுக்கு மதிய உணவு, மளிகைப் பொருட்கள், புதிய காய்கறிகள் அல்லது கொள்முதல் தேவைகள் எதுவும் உருவாக்கப்படாது.",
      markHolidayBtn: "விடுமுறையாகக் குறி",
      markHolidayPromptTitle: "விடுமுறை நாளாகக் குறிக்கவா?",
      markHolidayPromptMsg: "இந்த நாள் வேலை இல்லாத விடுமுறை நாளாகக் கருதப்படும். மதிய உணவு, மூலப்பொருள் அல்லது கொள்முதல் தேவைகள் எதுவும் உருவாக்கப்படாது.",
      removeHolidayBtn: "விடுமுறையை நீக்கு",
      removeHolidayPromptTitle: "விடுமுறையை நீக்கவா?",
      removeHolidayPromptMsg: "இந்த நாள் மீண்டும் சாதாரண வேலை நாளாக மாற்றப்படும்.",
      markedSuccess: "விடுமுறை நாளாக வெற்றிகரமாகக் குறிக்கப்பட்டது! 🎉",
      removedSuccess: "விடுமுறை நீக்கப்பட்டு சாதாரண வேலை நாள் மீட்டமைக்கப்பட்டது!",
      calendarTag: "விடுமுறை",
      noRequirements: "தேவைகள் ஏதுமில்லை"
    },
    topSection: {
      goodMorning: "காலை வணக்கம்",
      goodAfternoon: "மதிய வணக்கம்",
      goodEvening: "மாலை வணக்கம்",
      master: "மாஸ்டர்",
      subtitle: "நாளை மதிய உணவை நிர்வகித்து, உண்மையான நேரத்தில் சமையல் குறிப்புகளை உள்ளமைக்கவும்.",
      autoGen: "தானியக்கம்",
      autoGeneration: "தானியக்கம்",
      active: "செயலில்"
    },
    dashboard: {
      todayTitle: "இன்றைய மதிய உணவு மெனு",
      tomorrowTitle: "நாளைய மதிய உணவு மெனு",
      timeRange: "பிற்பகல் 1:00 – 2:00",
      noTodayMenu: "இன்று எந்த மெனுவும் உருவாக்கப்படவில்லை",
      noTodaySub: "மெனுக்கள் தினமும் இரவு 08:00 மணிக்கு தானாகவே உருவாக்கப்படும். நாளை திட்டமிட கீழே உள்ள பகுதியைப் பயன்படுத்தவும்.",
      preparedServed: "தயாரிக்கப்பட்டு பரிமாறப்பட்டது",
      notSelectedTitle: "நாளைய மெனு இன்னும் தேர்ந்தெடுக்கப்படவில்லை",
      notSelectedSub: "எங்கள் தனிப்பயன் சமையல் பரிந்துரை சக்கரத்தை இயக்க 'சுழற்று & தேர்ந்தெடு' என்பதைக் கிளிக் செய்யவும்.",
      btnRollSelect: "மெனுவைச் சுழற்றித் தேர்ந்தெடு",
      btnSkipMenu: "மெனுவைத் தவிர்",
      btnMessageChef: "சமையல்காரருக்கு அனுப்பு",
      carouselTitle: "நாளைய விருந்தைத் தேர்ந்தெடுக்கிறது...",
      spinPrompt: "சக்கரத்தை நிறுத்த கீழே கிளிக் செய்யவும்!",
      spinStopBtn: "சக்கரத்தை நிறுத்து",
      availableRecipes: "கிடைக்கக்கூடிய உணவுகளின் தொகுப்பு",
      availableRecipesSub: "தானியங்கி தினசரி திட்டமிடலுக்குத் தகுதியான செயலில் உள்ள உணவுகள்.",
      dishes: "உணவுகள்",
      available: "கிடைக்கும்",
      unavailable: "கிடைக்காது",
      category: "வகை",
      desc: "விளக்கம்",
      tomorrowSelectedTitle: "நாளைய மதிய உணவு தேர்ந்தெடுக்கப்பட்டது",
      skipAlert: "மதிய உணவு தவிர்க்கப்பட்டது. அடுத்த உணவு தேர்ந்தெடுக்கப்படுகிறது...",
      initAlert: "நாளைய மதிய உணவு மெனு உருவாக்கம் தொடங்கப்பட்டது...",
      noAvailableFoods: "கிடைக்கக்கூடிய உணவுகள் எதுவும் இல்லை",
      noAvailableFoodsSub: "மெனுக்களை உருவாக்கத் தொடங்க தயவுசெய்து 'உணவுகள்' தாவலில் சில உணவுகளைச் சேர்த்து, அவை 'கிடைக்கும்' நிலையில் இருப்பதை உறுதிசெய்யவும்.",
      failedFetch: "டாஷ்போர்டு தரவைப் பெறுவதில் தோல்வி"
    },
    foods: {
      title: "உணவுப் பொருட்களின் கோப்புத்தொகுப்பு",
      subtitle: "மெனு உருவாக்கத்திற்கான உணவு விருப்பங்களைச் சேர்க்கவும், திருத்தவும் அல்லது முடக்கவும்.",
      searchPlaceholder: "உணவுகளை பெயர் அல்லது வகை மூலம் தேடவும்...",
      addNew: "புதிய உணவைச் சேர்",
      category: "வகை",
      status: "நிலை",
      actions: "செயல்கள்",
      editDish: "உணவைத் திருத்து",
      addDish: "உணவைச் சேர்",
      dishName: "உணவின் பெயர்",
      dishNameEn: "உணவின் பெயர் (ஆங்கிலம்)",
      dishNameTa: "உணவின் பெயர் (தமிழ்)",
      dishDesc: "விளக்கம்",
      dishDescEn: "விளக்கம் (ஆங்கிலம்)",
      dishDescTa: "விளக்கம் (தமிழ்)",
      dishImage: "உணவின் படம்",
      uploadPrompt: "படத்தைப் பதிவேற்ற கிளிக் செய்யவும் அல்லது இழுத்து விடவும்",
      uploadFormats: "10MB வரை PNG, JPG, JPEG வடிவங்கள்",
      saving: "சேமிக்கப்படுகிறது...",
      successAdd: "உணவு வெற்றிகரமாகச் சேர்க்கப்பட்டது!",
      successEdit: "உணவு வெற்றிகரமாக மாற்றப்பட்டது!",
      failedFetch: "உணவுகளைப் பெறுவதில் தோல்வி",
      nameRequired: "பெயர் தேவை",
      confirmDelete: "இந்த உணவை நிச்சயமாக அழிக்க விரும்புகிறீர்களா?",
      successDelete: "உணவு வெற்றிகரமாக அழிக்கப்பட்டது!",
      failedDelete: "உணவை அழிப்பதில் தோல்வி",
      foodTypeLabel: "உணவு வகை",
      vegLabel: "சைவம் (Veg)",
      nonVegLabel: "அசைவம் (Non-Veg)"
    },
    history: {
      title: "மதிய உணவு வரலாற்று பதிவுகள்",
      subtitle: "முன்பு உருவாக்கப்பட்ட மெனுக்கள் மற்றும் தவிர்க்கப்பட்ட தேர்வுகளை மதிப்பாய்வு செய்யவும்.",
      searchPlaceholder: "வரலாற்றை உணவின் பெயர் அல்லது வகை மூலம் தேடவும்...",
      monthFilterPlaceholder: "அனைத்து மாதங்களும்",
      dish: "உணவு",
      servedOn: "பரிமாறப்பட்ட நாள்",
      generatedAt: "உருவாக்கப்பட்ட நேரம்",
      noHistoryRecords: "வரலாற்று பதிவுகள் எதுவும் இல்லை",
      noHistorySub: "நேற்று, இன்று அல்லது நாளைக்கான மதிய உணவு மெனுக்களை உருவாக்கியுள்ளதை உறுதிப்படுத்தவும்.",
      failedFetchHistory: "வரலாற்று பதிவுகளைப் பெறுவதில் தோல்வி"
    },
    calendar: {
      title: "ஊடாடும் மதிய உணவு நாட்காட்டி",
      subtitle: "நடப்பு மற்றும் வரவிருக்கும் வாரங்களுக்கான மெனுக்களைத் திட்டமிட்டுப் பார்க்கவும்.",
      today: "இன்று",
      prev: "முந்தைய",
      next: "அடுத்த",
      selectedMenuDetails: "தேர்ந்தெடுக்கப்பட்ட மெனு விவரங்கள்",
      noSelectedMenu: "மெனு எதுவும் உருவாக்கப்படவில்லை",
      clickAnyDay: "விவரங்களைக் காண தனிப்படுத்தப்பட்ட எந்த நாளையும் கிளிக் செய்யவும்.",
      failedFetchFoods: "கிடைக்கக்கூடிய உணவுகளைப் பெறுவதில் தோல்வி",
      Sunday: "ஞாயிறு",
      Monday: "திங்கள்",
      Tuesday: "செவ்வாய்",
      Wednesday: "புதன்",
      Thursday: "வியாழன்",
      Friday: "வெள்ளி",
      Saturday: "சனி"
    },
    statistics: {
      title: "உணவு நுண்ணறிவு & புள்ளிவிவரங்கள்",
      subtitle: "சமையல் குறிப்புகளின் பயன்பாடு, வகைகள் மற்றும் தவிர்க்கும் விகிதம் பற்றிய பகுப்பாய்வு.",
      totalDishes: "மொத்த உணவுகள்",
      activeDishes: "செயலில் உள்ள உணவுகள்",
      inactiveDishes: "செயலற்ற உணவுகள்",
      mostServed: "அதிகம் பரிமாறப்பட்ட உணவு",
      leastServed: "குறைவாகப் பரிமாறப்பட்ட உணவு",
      skipRate: "சராசரி தவிர் விகிதம்",
      categoryDistribution: "வகை விநியோகம்",
      servedTimeline: "பரிமாறப்பட்ட காலவரிசை",
      noChartData: "தரவு எதுவும் இல்லை. வெவ்வேறு பிரிவுகளில் உணவுகளைச் சேர்க்கவும்.",
      totalGenerations: "உருவாக்கப்பட்ட மெனுக்கள்",
      totalSkips: "தவிர்க்கப்பட்ட மெனுக்கள்",
      availabilityChart: "இருப்புச் சுருக்கம்"
    },
    settings: {
      title: "அமைப்பு அமைப்புகள்",
      subtitle: "நிர்வாக விருப்பங்கள் மற்றும் தரவுத்தள விதைப்பு விருப்பங்கள்.",
      dbSetup: "தரவுத்தள அமைப்பு",
      dbSetupSub: "டாஷ்போர்டை உடனடியாக நிரப்ப டெமோ உணவுகளை விதைக்கவும்.",
      preseedTitle: "பிரீமியம் உணவு மெனுவை முன்கூட்டியே விதைக்கவும்",
      preseedSub: "உயர்தர படங்கள் மற்றும் விளக்கங்களுடன் 10 வகையான உணவுகளை (முக்கிய உணவுகள், சாலடுகள், இனிப்புகள், பானங்கள்) சேர்க்கிறது.",
      btnSeed: "உணவுகளை விதைக்கவும்",
      seeding: "விதைக்கப்படுகிறது...",
      seedConfirm: "இது உங்கள் உணவுப் பட்டியலில் 10 முன்கூட்டியே உள்ளமைக்கப்பட்ட உணவுகளைச் சேர்க்கும். தொடரலாமா?",
      seedSuccess: "10 பிரீமியம் உணவுப் பொருட்களுடன் தரவுத்தளம் வெற்றிகரமாக விதைக்கப்பட்டது!",
      seedFailed: "தரவுத்தளத்தை விதைப்பதில் தோல்வி",
      schedulerConfig: "அமைப்பு திட்டமிடுபவர் உள்ளமைப்பு",
      schedulerSub: "மெஸ் மாஸ்டர் பின்னணி பணியாளர்கள் மற்றும் ஆட்டோமேஷன் நிலை.",
      cronStatus: "Node-Cron நிலை",
      cronActive: "செயலில் உள்ளது & இயங்குகிறது",
      triggerFreq: "தூண்டுதல் அதிர்வெண்",
      triggerTime: "தினமும் சரியாக இரவு 08:00 மணிக்கு (20:00)",
      targetAction: "இலக்கு நடவடிக்கை",
      targetActionDesc: "முந்தைய 5 நாட்களின் தேர்வுகளைத் தவிர்த்து நாளைய மெனுவை உருவாக்கவும்",
      dangerousSettings: "அபாயகரமான அமைப்புகள்",
      dangerousSub: "அழிவுகரமான செயல்கள். மிகுந்த எச்சரிக்கையுடன் பயன்படுத்தவும்.",
      resetDb: "தரவுத்தளத்தை மீட்டமைக்கவும்",
      resetDbSub: "அனைத்து உணவுப் பொருட்களையும் உருவாக்கப்பட்ட மெனுக்களையும் நீக்குகிறது. இதை மாற்ற முடியாது.",
      btnReset: "தரவை மீட்டமை",
      resetConfirm: "முக்கிய எச்சரிக்கை: அனைத்து தரவையும் அழிக்க நீங்கள் உறுதியாக இருக்கிறீர்களா? இது அனைத்து உணவுகளையும் மெனுக்களையும் அழித்துவிடும்.",
      resetInitiated: "தரவுத்தள மீட்பு தொடங்கப்பட்டது",
      resetFailed: "மீட்டமைப்பில் தோல்வி",
      langSelect: "மொழியைத் தேர்ந்தெடுக்கவும்",
      langSelectDesc: "உங்களுக்கு விருப்பமான இடைமுக மொழியைத் தேர்ந்தெடுக்கவும்.",
      chefConfig: "சமையல்காரர் தொடர்பு அமைப்புகள்",
      chefConfigSub: "தினசரி மெனு அறிவிப்புகளை சமையல்காரருக்கு வாட்ஸ்அப் அல்லது எஸ்எம்எஸ் மூலம் அனுப்ப தொடர்பு விவரங்களை உள்ளமைக்கவும்.",
      chefName: "சமையல்காரர் பெயர்",
      chefPhone: "சமையல்காரர் தொலைபேசி எண்",
      chefNamePlaceholder: "எ.கா. ராமு",
      chefPhonePlaceholder: "எ.கா. +919876543210",
      btnSaveChef: "அமைப்புகளைச் சேமி",
      chefConfigSaved: "சமையல்காரர் அமைப்புகள் வெற்றிகரமாகச் சேமிக்கப்பட்டன!",
      paymentConfig: "பணம் மற்றும் QR குறியீடு அமைப்புகள்",
      paymentConfigSub: "வாடிக்கையாளர் கட்டணத்திற்கான UPI மற்றும் வங்கி விவரங்களை உள்ளமைக்கவும்.",
      upiId: "UPI முகவரி (UPI ID)",
      upiName: "கணக்கு பெயர் (UPI Account Name)",
      upiAmount: "கட்டணத் தொகை (₹)",
      bankName: "வங்கி பெயர்",
      bankAcc: "வங்கி கணக்கு எண்",
      bankIfsc: "IFSC குறியீடு",
      btnSavePayment: "கட்டண அமைப்புகளைச் சேமி",
      paymentConfigSaved: "கட்டண அமைப்புகள் வெற்றிகரமாகச் சேமிக்கப்பட்டன!"
    },
    ingredients: {
      title: "மூலப்பொருட்கள் & மளிகைத் திட்டம்",
      subtitle: "தினசரி மதிய உணவுத் தேவைகளைக் கணக்கிட்டு, மளிகை இருப்பை நிர்வகித்து, மாதாந்திரக் கொள்முதலைத் திட்டமிடுங்கள்.",
      tabDaily: "தினசரி தேவைகள்",
      tabStorage: "மளிகை இருப்பு",
      tabMonthly: "மாதாந்திரத் திட்டம்",
      tabRecipes: "28 உணவு வகைகள்",
      todayLunch: "இன்றைய மதிய உணவு மெனு",
      selectDate: "தேதியைத் தேர்ந்தெடுக்கவும்",
      employeesApplied: "மதிய உணவிற்கு விண்ணப்பித்த ஊழியர்கள்",
      employeesAppliedDesc: "இந்த நாளில் மதிய உணவு உண்ணும் உண்மையான ஊழியர்களின் எண்ணிக்கை.",
      baseRecipeNotice: "அடிப்படை செய்முறை அளவு: 10 ஊழியர்கள்",
      formulaNotice: "தேவையான அளவு = (அடிப்படை அளவு / 10) × உண்மையான ஊழியர்கள்",
      groceryStorageHeader: "🏪 மளிகை / இருப்புப் பொருட்கள்",
      groceryStorageSub: "மளிகைக் கிடங்கில் பராமரிக்கப்படும் பொருட்கள். தற்போதைய இருப்புடன் ஒப்பிடப்படுகிறது.",
      freshItemsHeader: "🥬 இன்றைய புதிய காய்கறிகள் & பொருட்கள்",
      freshItemsSub: "தினமும் சந்தையில் புதிதாக வாங்க வேண்டிய காய்கறிகள்/இறைச்சி. கிடங்கு இருப்பிலிருந்து கழிக்கப்படாது.",
      purchaseListHeader: "🛒 இன்றைய கொள்முதல் பட்டியல்",
      purchaseListSub: "தேவையான அளவு தற்போதைய இருப்பை விட அதிகமாக உள்ள மளிகைப் பொருட்கள்.",
      allStockSufficient: "✅ தேவையான அனைத்துப் பொருட்களும் போதிய அளவில் இருப்பில் உள்ளன. இன்று கொள்முதல் தேவையில்லை.",
      confirmDeductBtn: "பயன்படுத்திய இருப்பை உறுதிசெய்து கழி",
      confirmDeductConfirm: "இன்றைய மதிய உணவுக்கான மளிகைப் பொருட்களை இருப்பிலிருந்து கழிக்க நிச்சயமாக விரும்புகிறீர்களா?",
      stockDeductedSuccess: "மளிகை இருப்பு வெற்றிகரமாகக் கழிக்கப்பட்டு புதுப்பிக்கப்பட்டது!",
      alreadyDeducted: "இந்த நாளுக்கான மளிகை இருப்பு ஏற்கனவே கழிக்கப்பட்டுவிட்டது",
      deductedOn: "கழிக்கப்பட்ட நேரம்",
      itemName: "பொருளின் பெயர்",
      required: "தேவை",
      available: "கிடங்கு இருப்பு",
      purchaseNeeded: "வாங்க வேண்டியவை",
      remainingAfterLunch: "மீதமுள்ள இருப்பு",
      unit: "அலகு",
      status: "நிலை",
      actions: "செயல்கள்",
      inStock: "இருப்பில் உள்ளது",
      lowStock: "குறைந்த இருப்பு",
      outOfStock: "இருப்பு இல்லை",
      addStockTitle: "இருப்பைச் சேர் / மாற்று",
      setStock: "நேரடி இருப்பு அமை",
      addAmount: "கூடுதல் அளவு சேர்",
      minThreshold: "குறைந்தபட்ச எச்சரிக்கை அளவு",
      suggestedStock: "பரிந்துரைக்கப்பட்ட நிலையான இருப்பு",
      updateStockSuccess: "இருப்பு வெற்றிகரமாகப் புதுப்பிக்கப்பட்டது!",
      monthlyTitle: "மாதாந்திர மளிகைக் கொள்முதல் திட்டம்",
      monthlySub: "ஒவ்வொரு நாளின் ஊழியர் எண்ணிக்கை மற்றும் திட்டமிடப்பட்ட மெனுக்களின் அடிப்படையில் தொகுக்கப்பட்ட மளிகைத் தேவை.",
      monthlyTotalRequired: "மாதாந்திரத் தேவை",
      extraPurchaseRequired: "கூடுதலாக வாங்க வேண்டியவை",
      totalDays: "மொத்த நாட்கள்",
      totalMeals: "திட்டமிடப்பட்ட மொத்த மதிய உணவுகள்",
      totalGroceryTypes: "மளிகைப் பொருட்களின் வகைகள்",
      shortfallItems: "வாங்க வேண்டிய மளிகைப் பொருட்கள்",
      copyList: "பட்டியலை நகலெடு",
      listCopied: "கொள்முதல் பட்டியல் நகலெடுக்கப்பட்டது!",
      shareWhatsapp: "வாட்ஸ்அப்பில் பகிர்",
      saveCount: "எண்ணிக்கையைச் சேமி",
      dishRecipeCount: "28 முன்கூட்டியே ஏற்றப்பட்ட உணவுகள்",
      searchDishes: "உணவு அல்லது மூலப்பொருளைத் தேடுக...",
      filterVeg: "சைவம் மட்டும்",
      filterNonVeg: "அசைவம்",
      filterAll: "அனைத்து உணவுகள்",
      storageStockSection: "மளிகை இருப்பு (STORAGE STOCK)",
      storageStockSub: "தற்போது இருப்பில் உள்ள மளிகைப் பொருட்கள் (> 0)",
      outOfStockSection: "இருப்பு இல்லை (OUT OF STOCK)",
      outOfStockSub: "இருப்பு தீர்ந்துவிட்ட பொருட்கள் (0 அளவு)",
      noInStockItems: "தற்போது மளிகை இருப்பு ஏதுமில்லை.",
      noOutOfStockItems: "அனைத்துப் பொருட்களும் இருப்பில் உள்ளன!",
      editRecipe: "செய்முறையைத் திருத்து",
      editRecipeTitle: "செய்முறை & மூலப்பொருட்கள் திருத்து",
      editRecipeSub: "10 நபர்களுக்கான அடிப்படை மூலப்பொருட்களின் அளவுகளை மாற்றியமைக்கவும்.",
      addIngredient: "மூலப்பொருளைச் சேர்",
      removeIngredient: "நீக்கு",
      confirmRemoveIngredient: "இந்த மூலப்பொருளை செய்முறையிலிருந்து நீக்க நிச்சயமாக விரும்புகிறீர்களா?",
      saveRecipeChanges: "மாற்றங்களைச் சேமி",
      recipeUpdatedSuccess: "செய்முறை வெற்றிகரமாகப் புதுப்பிக்கப்பட்டது! 🎉",
      recipeUpdateFailed: "செய்முறையைப் புதுப்பிப்பதில் தோல்வி",
      dishNameEn: "உணவுப் பெயர் (ஆங்கிலம்)",
      dishNameTa: "உணவுப் பெயர் (தமிழ்)",
      foodType: "உணவு வகை",
      category: "பிரிவு",
      description: "விவரம்",
      basePersonsLabel: "அடிப்படை பரிமாறும் அளவு",
      ingredientNameEn: "மூலப்பொருள் பெயர்",
      ingredientNameTa: "தமிழ் பெயர்",
      ingredientCategory: "வகை",
      baseQuantity: "அடிப்படை அளவு (10 பேர்)",
      unit: "அலகு",
      groceryCategory: "மளிகை / கிடங்கு",
      freshCategory: "புதிய காய்கறி/பொருட்கள்",
      deleteStorageTitle: "கிடங்கிலிருந்து நீக்கு",
      confirmDeleteStorage: "இந்த மளிகைப் பொருளை கிடங்கிலிருந்து நீக்க நிச்சயமாக விரும்புகிறீர்களா?",
      deleteStorageNote: "உணவு மற்றும் செய்முறைத் தேவைகள் பாதிக்கப்படாது.",
      storageDeletedSuccess: "கிடங்கிலிருந்து பொருள் வெற்றிகரமாக நீக்கப்பட்டது"
    }
  }
};

const categoryTranslations = {
  en: {
    'Main Course': 'Main Course',
    'Starter': 'Starter',
    'Dessert': 'Dessert',
    'Beverage': 'Beverage',
    'Salad': 'Salad',
    'Soup': 'Soup',
    'Special': 'Special'
  },
  ta: {
    'Main Course': 'முதன்மை உணவு',
    'Starter': 'துவக்க உணவு',
    'Dessert': 'இனிப்பு',
    'Beverage': 'பானம்',
    'Salad': 'சாலட்',
    'Soup': 'சূপ',
    'Special': 'சிறப்பு உணவு'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    window.dispatchEvent(new Event('language-change'));
  }, [language]);

  const t = React.useCallback((path) => {
    const keys = path.split('.');
    let value = translations[language] || translations['en'];
    for (const key of keys) {
      if (value && value[key] !== undefined) {
        value = value[key];
      } else {
        // fallback to english
        let fallback = translations['en'];
        for (const fkey of keys) {
          if (fallback && fallback[fkey] !== undefined) {
            fallback = fallback[fkey];
          } else {
            fallback = path; // return path if not found
          }
        }
        return fallback;
      }
    }
    return value;
  }, [language]);

  const tc = React.useCallback((category) => {
    return categoryTranslations[language]?.[category] || category;
  }, [language]);

  const contextValue = React.useMemo(() => ({
    language,
    setLanguage,
    t,
    tc
  }), [language, t, tc]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};
